// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaliczenie_JiPP5v2.Context;

namespace Zaliczenie_JiPP5v2.Migrations
{
    [DbContext(typeof(ProduktContext))]
    [Migration("20230122172348_InitialProduktv2")]
    partial class InitialProduktv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zaliczenie_JiPP5v2.Models.ProduktModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DATA_KUPNA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ILOSC")
                        .HasColumnType("int");

                    b.Property<string>("JEDNOSTKA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KATEGORIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOKALIZACJA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAZWA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produkty");
                });
#pragma warning restore 612, 618
        }
    }
}
